/**
 * Dados de serviços importados da planilha
 * Gerado automaticamente em: 2026-01-03T15:24:30.708Z
 * Total: 303 serviços em 27 categorias
 */

export interface ServiceData {
  id: string;
  externalCode: string;
  name: string;
  categoryId: string;
  categoryName: string;
  price: number;
  durationMinutes: number;
  isActive: boolean;
}

export interface CategoryData {
  id: string;
  name: string;
  slug: string;
  servicesCount: number;
}

export const importedCategories: CategoryData[] = [
  {
    id: "cat-1",
    name: "Com Ceras",
    slug: "com-ceras",
    servicesCount: 50,
  },
  {
    id: "cat-2",
    name: "Roll-on",
    slug: "roll-on",
    servicesCount: 17,
  },
  {
    id: "cat-3",
    name: "Corporal",
    slug: "corporal",
    servicesCount: 38,
  },
  {
    id: "cat-4",
    name: "Acupuntura",
    slug: "acupuntura",
    servicesCount: 1,
  },
  {
    id: "cat-5",
    name: "Manicure",
    slug: "manicure",
    servicesCount: 13,
  },
  {
    id: "cat-6",
    name: "Outros",
    slug: "outros",
    servicesCount: 21,
  },
  {
    id: "cat-7",
    name: "Alongamento de Unhas",
    slug: "alongamento-de-unhas",
    servicesCount: 8,
  },
  {
    id: "cat-8",
    name: "Colorações",
    slug: "coloracoes",
    servicesCount: 8,
  },
  {
    id: "cat-9",
    name: "Sobrancelhas",
    slug: "sobrancelhas",
    servicesCount: 8,
  },
  {
    id: "cat-10",
    name: "Facial",
    slug: "facial",
    servicesCount: 29,
  },
  {
    id: "cat-11",
    name: "Alongamentos",
    slug: "alongamentos",
    servicesCount: 5,
  },
  {
    id: "cat-12",
    name: "Podologia",
    slug: "podologia",
    servicesCount: 17,
  },
  {
    id: "cat-13",
    name: "Egípcia (Linha)",
    slug: "egipcia-linha",
    servicesCount: 7,
  },
  {
    id: "cat-14",
    name: "Penteados",
    slug: "penteados",
    servicesCount: 3,
  },
  {
    id: "cat-15",
    name: "Mechas",
    slug: "mechas",
    servicesCount: 5,
  },
  {
    id: "cat-16",
    name: "Tratamentos",
    slug: "tratamentos",
    servicesCount: 15,
  },
  {
    id: "cat-17",
    name: "Cílios",
    slug: "cilios",
    servicesCount: 7,
  },
  {
    id: "cat-18",
    name: "Pedicure",
    slug: "pedicure",
    servicesCount: 12,
  },
  {
    id: "cat-19",
    name: "Cortes",
    slug: "cortes",
    servicesCount: 7,
  },
  {
    id: "cat-20",
    name: "Maquiagem",
    slug: "maquiagem",
    servicesCount: 9,
  },
  {
    id: "cat-21",
    name: "Styling",
    slug: "styling",
    servicesCount: 9,
  },
  {
    id: "cat-22",
    name: "Massagens Diversas",
    slug: "massagens-diversas",
    servicesCount: 5,
  },
  {
    id: "cat-23",
    name: "Serviços de Lavatório",
    slug: "servicos-de-lavatorio",
    servicesCount: 1,
  },
  {
    id: "cat-24",
    name: "Barba",
    slug: "barba",
    servicesCount: 1,
  },
  {
    id: "cat-25",
    name: "Massagens em Maca",
    slug: "massagens-em-maca",
    servicesCount: 1,
  },
  {
    id: "cat-26",
    name: "Micropigmentação",
    slug: "micropigmentacao",
    servicesCount: 4,
  },
  {
    id: "cat-27",
    name: "Alisamentos e Cachos",
    slug: "alisamentos-e-cachos",
    servicesCount: 2,
  },
];

export const importedServices: ServiceData[] = [
  {
    id: "srv-1",
    externalCode: "DC1",
    name: "1/2 Intima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 49,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-2",
    externalCode: "DC2",
    name: "1/2 Perna",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-3",
    externalCode: "DR1",
    name: "1/2 Perna Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 50,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-4",
    externalCode: "EC1",
    name: "Abdômen Redux",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 115,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-5",
    externalCode: "B1",
    name: "Acupuntura (Sistemica/Craniopuntura/Auricular)",
    categoryId: "cat-4",
    categoryName: "Acupuntura",
    price: 140,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-6",
    externalCode: "MP1",
    name: "Adesivos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 14,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-7",
    externalCode: "EG1",
    name: "Adicional pacote estética",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 105,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-8",
    externalCode: "MP2",
    name: "Alongamento em Unhas",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 190,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-9",
    externalCode: "DC3",
    name: "Ânus",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 50,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-10",
    externalCode: "EC2",
    name: "Aparelho Striat + Dermocosmetico e Laser",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 184,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-11",
    externalCode: "C62",
    name: "Aplicação Coloração",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 100,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-12",
    externalCode: "SB7",
    name: "Aplicação de Henna (produto cliente)",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 35,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-13",
    externalCode: "SB2",
    name: "Aplicação de Henna (produto profi.)",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 60,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-14",
    externalCode: "EF1",
    name: "Aplicação de Ozônio",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 260,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-15",
    externalCode: "C1",
    name: "Aplicação de Tela (100gr/150gr/200gr)",
    categoryId: "cat-11",
    categoryName: "Alongamentos",
    price: 885,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-16",
    externalCode: "EC36",
    name: "Ativos Intramuscular (Emagrecimento)",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 199,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-17",
    externalCode: "MP3",
    name: "Avaliação",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 0,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-18",
    externalCode: "EC3",
    name: "Avaliação",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 0,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-19",
    externalCode: "C2",
    name: "Avaliação cabelo",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 0,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-20",
    externalCode: "DC4",
    name: "Axilas",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 28,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-21",
    externalCode: "DL1",
    name: "Axilas (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 45,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-22",
    externalCode: "DC5",
    name: "Axilas Grátis",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 0,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-23",
    externalCode: "C3",
    name: "baby liss",
    categoryId: "cat-14",
    categoryName: "Penteados",
    price: 85,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-24",
    externalCode: "C4",
    name: "Balayage- a partir de",
    categoryId: "cat-15",
    categoryName: "Mechas",
    price: 280,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-25",
    externalCode: "C5",
    name: "Banho de Brilho",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 124,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-26",
    externalCode: "MP4",
    name: "Banho de Gel",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 90,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-27",
    externalCode: "DC6",
    name: "Barriga",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 59,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-28",
    externalCode: "DR2",
    name: "Barriga Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 50,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-29",
    externalCode: "EF2",
    name: "BB Glow Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 179,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-30",
    externalCode: "EF3",
    name: "Bioestimulador de Colágeno (Radiesse)",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 1400,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-31",
    externalCode: "EF4",
    name: "Bioestimulador de Colágeno (Sculptra)",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 2200,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-32",
    externalCode: "EC49",
    name: "Bioestimulador Elleva",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 1850,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-33",
    externalCode: "EC50",
    name: "Bioestimulador Elleva X",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 3300,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-34",
    externalCode: "EP1",
    name: "Bioestimulador pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 1900,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-35",
    externalCode: "EC4",
    name: "Bioimpedância",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 120,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-36",
    externalCode: "EF30",
    name: "Blefaroplastia JP",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 485,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-37",
    externalCode: "MP6",
    name: "Blindagem",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 120,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-38",
    externalCode: "C6",
    name: "Botox / Selagem",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 176,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-39",
    externalCode: "EC60",
    name: "Botox Axilas Sudorese",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 1350,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-40",
    externalCode: "C7",
    name: "Botox Capilar- a partir de",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 176,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-41",
    externalCode: "EF5",
    name: "Botox Facial Testa",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 600,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-42",
    externalCode: "EF6",
    name: "Botox Glabela",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 350,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-43",
    externalCode: "EF7",
    name: "Botox Lateral olhos",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 380,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-44",
    externalCode: "DC7",
    name: "Braços",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 69,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-45",
    externalCode: "DR3",
    name: "Braços Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 50,
    durationMinutes: 25,
    isActive: true,
  },
  {
    id: "srv-46",
    externalCode: "CL1",
    name: "Brow Lamination",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 95,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-47",
    externalCode: "DC8",
    name: "Buço",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 22,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-48",
    externalCode: "DL2",
    name: "Buço (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 32,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-49",
    externalCode: "DC9",
    name: "Buço Grátis",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 0,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-50",
    externalCode: "C8",
    name: "Californiana/ Ombre Hair- a partir de",
    categoryId: "cat-15",
    categoryName: "Mechas",
    price: 270,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-51",
    externalCode: "MP7",
    name: "Calosidade",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 85,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-52",
    externalCode: "C9",
    name: "Cauterização",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-53",
    externalCode: "C10",
    name: "Cauterização Vegana",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 195,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-54",
    externalCode: "MP8",
    name: "Chinelo Descartável",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 7,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-55",
    externalCode: "CL2",
    name: "Cílios Brasileiro",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 200,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-56",
    externalCode: "CL3",
    name: "Cilios fio a fio",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 80,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-57",
    externalCode: "CL4",
    name: "Cílios Manuteção de 55 à 80",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 80,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-58",
    externalCode: "CL5",
    name: "Cílios Remoção",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 35,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-59",
    externalCode: "CL6",
    name: "Cílios VL. Russo",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-60",
    externalCode: "MP9",
    name: "Colocação Unhas Postiças (Cliente)",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 19,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-61",
    externalCode: "MP10",
    name: "Colocação Unhas Postiças (profissional)",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 25,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-62",
    externalCode: "C11",
    name: "Coloração + Escova + Hidratação",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 260,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-63",
    externalCode: "C12",
    name: "Coloração/ Tonalizante- a partir de",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 125,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-64",
    externalCode: "C13",
    name: "Combo Coloração + Escova",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 173,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-65",
    externalCode: "C14",
    name: "Confecção + Aplicação (100gr/150gr/200gr)",
    categoryId: "cat-11",
    categoryName: "Alongamentos",
    price: 1490,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-66",
    externalCode: "C15",
    name: "Confecção da Tela (100gr/150gr/200gr)",
    categoryId: "cat-11",
    categoryName: "Alongamentos",
    price: 650,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-67",
    externalCode: "MP11",
    name: "Cortar Lixar Mão",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 22,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-68",
    externalCode: "MP12",
    name: "Cortar Lixar Pé",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 22,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-69",
    externalCode: "C16",
    name: "Corte + Escova",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 110,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-70",
    externalCode: "C17",
    name: "Corte com Secagem",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 81,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-71",
    externalCode: "PD001",
    name: "Corte de Unha",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 72,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-72",
    externalCode: "C18",
    name: "Corte Feminino",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 70,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-73",
    externalCode: "C19",
    name: "Corte Franja",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 31,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-74",
    externalCode: "C20",
    name: "Corte Infantil",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 45,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-75",
    externalCode: "C21",
    name: "Corte Masculino",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 45,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-76",
    externalCode: "C22",
    name: "Corte Pézinho",
    categoryId: "cat-19",
    categoryName: "Cortes",
    price: 26,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-77",
    externalCode: "DC10",
    name: "Costas",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 59,
    durationMinutes: 25,
    isActive: true,
  },
  {
    id: "srv-78",
    externalCode: "DR4",
    name: "Costas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 50,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-79",
    externalCode: "DC11",
    name: "Costeletas",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 22,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-80",
    externalCode: "DL3",
    name: "Costeletas (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 32,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-81",
    externalCode: "DC12",
    name: "Coxas",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 78,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-82",
    externalCode: "DR5",
    name: "Coxas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 53,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-83",
    externalCode: "C23",
    name: "Cronograma Braé",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 110,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-84",
    externalCode: "C24",
    name: "Cronograma Capilar (03 trat. + 01 cauteri.)",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 594,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-85",
    externalCode: "C25",
    name: "Cronograma Capilar c/ Ozônio",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 90,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-86",
    externalCode: "MP54",
    name: "Curativo",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 50,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-87",
    externalCode: "MK1",
    name: "Curso Aperfeiçoamento maquiagem",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 1300,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-88",
    externalCode: "MK2",
    name: "Curso Automaquiagem",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 380,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-89",
    externalCode: "MK3",
    name: "Curso Profissional de Maquiagem",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 2100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-90",
    externalCode: "MP55",
    name: "Debastamento Plantar",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 90,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-91",
    externalCode: "MK10",
    name: "Debutante",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 1490,
    durationMinutes: 240,
    isActive: true,
  },
  {
    id: "srv-92",
    externalCode: "C26",
    name: "Definição Modelagem a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 155,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-93",
    externalCode: "EC45",
    name: "Definição musular Glúteo",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 330,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-94",
    externalCode: "C27",
    name: "Definição Natural",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 105,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-95",
    externalCode: "C28",
    name: "Descoloração- a partir de",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 325,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-96",
    externalCode: "MP49",
    name: "Desencravar unha",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 160,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-97",
    externalCode: "SB5",
    name: "Design (linha)",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 65,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-98",
    externalCode: "DL4",
    name: "Design (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 65,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-99",
    externalCode: "SB1",
    name: "Design (pinça)",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 57,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-100",
    externalCode: "SB3",
    name: "Design c/ Henna",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 70,
    durationMinutes: 50,
    isActive: true,
  },
  {
    id: "srv-101",
    externalCode: "SB6",
    name: "Design Cera",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 57,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-102",
    externalCode: "EC34",
    name: "Drenagem corporal",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 180,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-103",
    externalCode: "EC48",
    name: "Drenagem Linfática Corporal Manual",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 195,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-104",
    externalCode: "EF32",
    name: "Drenagem Linfática Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 110,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-105",
    externalCode: "EC11",
    name: "Drenagem Modeladora ou Relaxante",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 120,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-106",
    externalCode: "EP12",
    name: "Drenagem pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 300,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-107",
    externalCode: "EC12",
    name: "Drenagem Pré ou Pós Cirurgica",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 110,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-108",
    externalCode: "EC46",
    name: "Eletroestimulação",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 110,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-109",
    externalCode: "EP3",
    name: "Eletroestimulação pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 200,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-110",
    externalCode: "EC14",
    name: "Endermoterapia",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 90,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-111",
    externalCode: "EC19",
    name: "Endolaser",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 4600,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-112",
    externalCode: "EG2",
    name: "Enzimas",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 300,
    durationMinutes: 50,
    isActive: true,
  },
  {
    id: "srv-113",
    externalCode: "EP2",
    name: "Enzimas pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 300,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-114",
    externalCode: "EP4",
    name: "Enzimas SC pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 200,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-115",
    externalCode: "EC35",
    name: "Escalda pés",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 975,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-116",
    externalCode: "C29",
    name: "Escova + Modelagem",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 118,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-117",
    externalCode: "C30",
    name: "Escova- a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 94,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-118",
    externalCode: "C31",
    name: "Escova Cacheada- a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 114,
    durationMinutes: 50,
    isActive: true,
  },
  {
    id: "srv-119",
    externalCode: "C32",
    name: "Escova Definitiva",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 600,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-120",
    externalCode: "C33",
    name: "Escova Progressiva c/ Formol- a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 225,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-121",
    externalCode: "C34",
    name: "Escova Progressiva s/ Formol- a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 270,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-122",
    externalCode: "C35",
    name: "Escova Progressiva s/ Formol- Masculino- a partir de",
    categoryId: "cat-21",
    categoryName: "Styling",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-123",
    externalCode: "EC52",
    name: "Esfoliação Corporal",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-124",
    externalCode: "MP13",
    name: "Esmaltação infantil- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 17,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-125",
    externalCode: "MP14",
    name: "Esmaltação Infantil- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 17,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-126",
    externalCode: "MP15",
    name: "Esmaltação- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 28,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-127",
    externalCode: "MP16",
    name: "Esmaltação- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 28,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-128",
    externalCode: "DC13",
    name: "Faixa",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 31,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-129",
    externalCode: "DR6",
    name: "Faixas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 19,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-130",
    externalCode: "MP18",
    name: "Fibra de Memória",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 55,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-131",
    externalCode: "EF11",
    name: "Fios de PDO (Dra. Emília)",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 1000,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-132",
    externalCode: "B2",
    name: "Fisioterapia Neurológica",
    categoryId: "cat-22",
    categoryName: "Massagens Diversas",
    price: 170,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-133",
    externalCode: "MP19",
    name: "Florzinha (cada)- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 9,
    durationMinutes: 2,
    isActive: true,
  },
  {
    id: "srv-134",
    externalCode: "MP20",
    name: "Florzinha (cada)- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 9,
    durationMinutes: 2,
    isActive: true,
  },
  {
    id: "srv-135",
    externalCode: "MP21",
    name: "Francesinha colorida- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 19,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-136",
    externalCode: "MP22",
    name: "Francesinha colorida- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 19,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-137",
    externalCode: "MP23",
    name: "Francesinha- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 17,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-138",
    externalCode: "MP24",
    name: "Francesinha- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 17,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-139",
    externalCode: "C36",
    name: "Free Hands",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 305,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-140",
    externalCode: "EF35",
    name: "Gerenciamento de Melasma",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 425,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-141",
    externalCode: "EC17",
    name: "Heccus",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 90,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-142",
    externalCode: "c59",
    name: "Hidratação + Escova promo",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 109,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-143",
    externalCode: "C37",
    name: "Hidratação/ Nutrição/ Reconstrução",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 138,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-144",
    externalCode: "EC18",
    name: "Hidro Ultrassônica",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 130,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-145",
    externalCode: "EP5",
    name: "Hidrolipo pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 300,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-146",
    externalCode: "EC42",
    name: "Hidrolipoclasia não apirativa",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 235,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-147",
    externalCode: "EF12",
    name: "Higienização Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 80,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-148",
    externalCode: "EC44",
    name: "Hipertrofia Muscular Região",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 230,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-149",
    externalCode: "MP25",
    name: "Insatisfação c/ cor- mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 20,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-150",
    externalCode: "MP26",
    name: "Insatisfação c/ cor- pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 20,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-151",
    externalCode: "DC14",
    name: "Intima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 55,
    durationMinutes: 25,
    isActive: true,
  },
  {
    id: "srv-152",
    externalCode: "EC38",
    name: "Intradermoterapia - Celulite",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 175,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-153",
    externalCode: "EC39",
    name: "Intradermoterapia - Estrias",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 275,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-154",
    externalCode: "EC40",
    name: "Intradermoterapia - Flacidez",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 195,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-155",
    externalCode: "EC37",
    name: "Intradermoterapia - Gostura localizada",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 160,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-156",
    externalCode: "EC41",
    name: "Intradermoterapia/ Mesoterapia Capilar",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 185,
    durationMinutes: 40,
    isActive: true,
  },
  {
    id: "srv-157",
    externalCode: "EF13",
    name: "Jato de Plasma",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 250,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-158",
    externalCode: "CL7",
    name: "Lash Lifting",
    categoryId: "cat-17",
    categoryName: "Cílios",
    price: 120,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-159",
    externalCode: "C38",
    name: "Lavagem Simples + Secar",
    categoryId: "cat-23",
    categoryName: "Serviços de Lavatório",
    price: 48,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-160",
    externalCode: "C61",
    name: "Led Terapia/C escova",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 240,
    durationMinutes: 50,
    isActive: true,
  },
  {
    id: "srv-161",
    externalCode: "EP7",
    name: "Limpeza avançada pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 350,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-162",
    externalCode: "EF28",
    name: "Limpeza de pele avançada",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 300,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-163",
    externalCode: "EF18",
    name: "Limpeza de pele simples",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 190,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-164",
    externalCode: "DC15",
    name: "Limpeza de Sobrancelhas (com ceras)",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 54,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-165",
    externalCode: "EF19",
    name: "Lipo de papada enzimática",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 385,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-166",
    externalCode: "C39",
    name: "Luzes / mechas Feminina- a partir de",
    categoryId: "cat-15",
    categoryName: "Mechas",
    price: 380,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-167",
    externalCode: "C40",
    name: "Luzes- Masculino",
    categoryId: "cat-15",
    categoryName: "Mechas",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-168",
    externalCode: "MP27",
    name: "Manutenção Alongamento",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 145,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-169",
    externalCode: "MP28",
    name: "Manutenção Banho Gel",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 80,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-170",
    externalCode: "C41",
    name: "Manutenção Mega Hair",
    categoryId: "cat-11",
    categoryName: "Alongamentos",
    price: 350,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-171",
    externalCode: "C42",
    name: "Manutenção Tela (100gr/150gr/200gr)",
    categoryId: "cat-11",
    categoryName: "Alongamentos",
    price: 840,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-172",
    externalCode: "MP29",
    name: "Mãos",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 39,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-173",
    externalCode: "MP30",
    name: "Mãos (masculino)",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 42,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-174",
    externalCode: "MK4",
    name: "Maquiagem Express",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 80,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-175",
    externalCode: "MK5",
    name: "Maquiagem Express (Cortesia)",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 30,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-176",
    externalCode: "MK6",
    name: "Maquiagem Infantil",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 40,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-177",
    externalCode: "MK7",
    name: "Maquiagem Noiva",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 200,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-178",
    externalCode: "MK8",
    name: "Maquiagem Social",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 240,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-179",
    externalCode: "DC16",
    name: "Masc- Abdome Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-180",
    externalCode: "DR7",
    name: "Masc- Abdome Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 68,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-181",
    externalCode: "C43",
    name: "Masc- Barba",
    categoryId: "cat-24",
    categoryName: "Barba",
    price: 37,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-182",
    externalCode: "DR8",
    name: "Masc-1/2 Perna Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 68,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-183",
    externalCode: "DC17",
    name: "Masc-Abdome+Tórax Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 119,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-184",
    externalCode: "DR9",
    name: "Masc-Abdome+Torax Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 99,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-185",
    externalCode: "DC18",
    name: "Masc-Ânus Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-186",
    externalCode: "DC19",
    name: "Masc-Axilas Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 55,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-187",
    externalCode: "DC20",
    name: "Masc-Barba Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-188",
    externalCode: "DC21",
    name: "Masc-Braços Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 85,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-189",
    externalCode: "DR10",
    name: "Masc-Braços Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 62,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-190",
    externalCode: "DC22",
    name: "Masc-Costas Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-191",
    externalCode: "DR11",
    name: "Masc-Costas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 68,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-192",
    externalCode: "DC23",
    name: "Masc-Faixa Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 36,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-193",
    externalCode: "DR12",
    name: "Masc-Faixa Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 24,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-194",
    externalCode: "DC24",
    name: "Masc-Mamilos Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 36,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-195",
    externalCode: "DC25",
    name: "Masc-Nádegas Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-196",
    externalCode: "DR13",
    name: "Masc-Nádegas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 56,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-197",
    externalCode: "DC26",
    name: "Masc-Nariz Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 45,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-198",
    externalCode: "DC27",
    name: "Masc-Orelha Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 45,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-199",
    externalCode: "DC28",
    name: "Masc-PC Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 110,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-200",
    externalCode: "DR14",
    name: "Masc-PC Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 84,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-201",
    externalCode: "DC29",
    name: "Masc-Pescoço Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 65,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-202",
    externalCode: "DC30",
    name: "Masc-Queixo Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 39,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-203",
    externalCode: "SB8",
    name: "Masc-Sobrancelhas Quente",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 53,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-204",
    externalCode: "DC31",
    name: "Masc-Torax Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-205",
    externalCode: "DR15",
    name: "Masc-Torax Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 68,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-206",
    externalCode: "DC32",
    name: "Masc-Virilha Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 79,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-207",
    externalCode: "DC33",
    name: "Masc-Virilha+Ânus Quente",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 125,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-208",
    externalCode: "B3",
    name: "Massagem Doin",
    categoryId: "cat-22",
    categoryName: "Massagens Diversas",
    price: 180,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-209",
    externalCode: "B4",
    name: "Massagem Facial",
    categoryId: "cat-22",
    categoryName: "Massagens Diversas",
    price: 60,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-210",
    externalCode: "B5",
    name: "Massagem Modeladora ou Localizada",
    categoryId: "cat-25",
    categoryName: "Massagens em Maca",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-211",
    externalCode: "B6",
    name: "Massagem Pedras Quentes",
    categoryId: "cat-22",
    categoryName: "Massagens Diversas",
    price: 180,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-212",
    externalCode: "EC26",
    name: "Massagem Relaxante",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-213",
    externalCode: "EC27",
    name: "Massagem Relaxante c/ Ventosa",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-214",
    externalCode: "C45",
    name: "Matização",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 118,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-215",
    externalCode: "EP13",
    name: "Mesobotox pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 600,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-216",
    externalCode: "EF20",
    name: "Microagulhamento",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 340,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-217",
    externalCode: "EF21",
    name: "Microagulhamento Skinbooster",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 535,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-218",
    externalCode: "MC7",
    name: "Micropigmentação Labial",
    categoryId: "cat-26",
    categoryName: "Micropigmentação",
    price: 600,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-219",
    externalCode: "MK9",
    name: "Modelo Maquiagem",
    categoryId: "cat-20",
    categoryName: "Maquiagem",
    price: 400,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-220",
    externalCode: "C47",
    name: "Morena Iluminada",
    categoryId: "cat-15",
    categoryName: "Mechas",
    price: 250,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-221",
    externalCode: "DC34",
    name: "Nadegas",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 59,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-222",
    externalCode: "DR16",
    name: "Nádegas Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 56,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-223",
    externalCode: "MC4",
    name: "Nanopigmentação",
    categoryId: "cat-26",
    categoryName: "Micropigmentação",
    price: 480,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-224",
    externalCode: "DC35",
    name: "Nariz",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 26,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-225",
    externalCode: "MO1",
    name: "Noiva avulso",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 1750,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-226",
    externalCode: "C48",
    name: "Nutrição + Escova",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-227",
    externalCode: "MP52",
    name: "Órteses",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-228",
    externalCode: "EF22",
    name: "Peeling de Rose de Mer",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 560,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-229",
    externalCode: "EP9",
    name: "Peeling pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 500,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-230",
    externalCode: "EF23",
    name: "Peeling químico",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 300,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-231",
    externalCode: "EC43",
    name: "PEIM ( Secagam de Vasinhos)",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 195,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-232",
    externalCode: "EF27",
    name: "Pele do Rosto a Laser ou Ozonio",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 300,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-233",
    externalCode: "C49",
    name: "Penteado Noiva",
    categoryId: "cat-14",
    categoryName: "Penteados",
    price: 250,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-234",
    externalCode: "C50",
    name: "Penteado Simples",
    categoryId: "cat-14",
    categoryName: "Penteados",
    price: 237,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-235",
    externalCode: "DC36",
    name: "Perna Completa",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 88,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-236",
    externalCode: "DR17",
    name: "Perna Completa Roll-on",
    categoryId: "cat-2",
    categoryName: "Roll-on",
    price: 68,
    durationMinutes: 25,
    isActive: true,
  },
  {
    id: "srv-237",
    externalCode: "MP33",
    name: "Pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 41,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-238",
    externalCode: "DC37",
    name: "Pés (com outro item)",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 19,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-239",
    externalCode: "MP34",
    name: "Pés (masculino)",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 44,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-240",
    externalCode: "MP35",
    name: "Pés Diabéticos",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 84,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-241",
    externalCode: "MP36",
    name: "Pés Rachados",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 84,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-242",
    externalCode: "DC38",
    name: "Pescoço",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 26,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-243",
    externalCode: "DL5",
    name: "Pescoço (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 36,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-244",
    externalCode: "MP38",
    name: "Plástica dos pés",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 65,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-245",
    externalCode: "MP37",
    name: "Plástica dos Pés + (mãos)",
    categoryId: "cat-5",
    categoryName: "Manicure",
    price: 35,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-246",
    externalCode: "MP39",
    name: "Plástica dos Pés + (Pés)",
    categoryId: "cat-18",
    categoryName: "Pedicure",
    price: 35,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-247",
    externalCode: "MP40",
    name: "Podologia",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 200,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-248",
    externalCode: "EC51",
    name: "Preenchimento Bumbum (1ml) + Retorno",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 1600,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-249",
    externalCode: "EF24",
    name: "Preenchimento Mandíbula /Labial / Chinês   (1mL)",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 900,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-250",
    externalCode: "DC39",
    name: "Promo 2ª a 4ª 1/2 Ìntima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 43,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-251",
    externalCode: "DC40",
    name: "Promo 2ª a 4ª Ânus",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 43,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-252",
    externalCode: "DC41",
    name: "Promo 2ª a 4ª Ìntima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 43,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-253",
    externalCode: "DC42",
    name: "Promo 2ª a 4ª V. Cavada",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 43,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-254",
    externalCode: "DC43",
    name: "Promo Maluca 1/2 Íntima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 215,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-255",
    externalCode: "DC44",
    name: "Promo Maluca Ânus",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 215,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-256",
    externalCode: "DC45",
    name: "Promo Maluca Íntima",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 215,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-257",
    externalCode: "DC46",
    name: "Promo Maluca V. Cavada",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 215,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-258",
    externalCode: "C51",
    name: "Promo Vita Color (Hidrat + Escova)",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 150,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-259",
    externalCode: "EC28",
    name: "Pump Up",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 90,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-260",
    externalCode: "DC47",
    name: "Queixo",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 26,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-261",
    externalCode: "DL6",
    name: "Queixo (linha)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 34,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-262",
    externalCode: "EC29",
    name: "Quick massagem 15 minutos",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 25,
    durationMinutes: 15,
    isActive: true,
  },
  {
    id: "srv-263",
    externalCode: "EP11",
    name: "Radiesse pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 1400,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-264",
    externalCode: "EC25",
    name: "Radiofrequência Corporal",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 205,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-265",
    externalCode: "EF34",
    name: "Radiofrequência Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 140,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-266",
    externalCode: "EP6",
    name: "Radriofrequencia pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 75,
    durationMinutes: 10,
    isActive: true,
  },
  {
    id: "srv-267",
    externalCode: "C52",
    name: "Reconstrução c/ Ozônio",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 90,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-268",
    externalCode: "MP43",
    name: "Reflexologia",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 75,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-269",
    externalCode: "C53",
    name: "Relaxamento- a partir de",
    categoryId: "cat-27",
    categoryName: "Alisamentos e Cachos",
    price: 180,
    durationMinutes: 120,
    isActive: true,
  },
  {
    id: "srv-270",
    externalCode: "C54",
    name: "Relaxamento- Masculino",
    categoryId: "cat-27",
    categoryName: "Alisamentos e Cachos",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-271",
    externalCode: "EF31",
    name: "Remoção de Verruga JP (Unidade)",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 350,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-272",
    externalCode: "MP45",
    name: "Reposição de unhas (alongamento)",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 20,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-273",
    externalCode: "EC30",
    name: "Retirada de Queloide + retorno",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 450,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-274",
    externalCode: "MP46",
    name: "Retirada do Gel e Fibra",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 40,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-275",
    externalCode: "MC5",
    name: "Retoque (Micropigmentação)",
    categoryId: "cat-26",
    categoryName: "Micropigmentação",
    price: 0,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-276",
    externalCode: "C55",
    name: "Retoque Raiz- a partir de",
    categoryId: "cat-8",
    categoryName: "Colorações",
    price: 127,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-277",
    externalCode: "EF33",
    name: "Revitalização Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 190,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-278",
    externalCode: "DL7",
    name: "Rosto Completo (linha)(não inclui sobrancelhas)",
    categoryId: "cat-13",
    categoryName: "Egípcia (Linha)",
    price: 65,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-279",
    externalCode: "DC48",
    name: "Rosto Completo (não inclui sobrancelhas)",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 55,
    durationMinutes: 20,
    isActive: true,
  },
  {
    id: "srv-280",
    externalCode: "EC32",
    name: "Secagem de vazos",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 200,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-281",
    externalCode: "DC49",
    name: "Seios (com outro item)",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 19,
    durationMinutes: 5,
    isActive: true,
  },
  {
    id: "srv-282",
    externalCode: "B9",
    name: "Shiatsu",
    categoryId: "cat-22",
    categoryName: "Massagens Diversas",
    price: 180,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-283",
    externalCode: "EF25",
    name: "Skinbooster",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 320,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-284",
    externalCode: "EP8",
    name: "Skinbooster pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 100,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-285",
    externalCode: "MC6",
    name: "Sobrancelhas (Micropigmentação)",
    categoryId: "cat-26",
    categoryName: "Micropigmentação",
    price: 450,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "srv-286",
    externalCode: "SB4",
    name: "Spa das Sobrancelhas",
    categoryId: "cat-9",
    categoryName: "Sobrancelhas",
    price: 75,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-287",
    externalCode: "MP47",
    name: "Spa dos Pés",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 70,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-288",
    externalCode: "EF40",
    name: "Terapia Capilar",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 250,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-289",
    externalCode: "EP10",
    name: "Toxina Botulínica pct",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 300,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-290",
    externalCode: "C56",
    name: "Tratamento + Escova",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 185,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-291",
    externalCode: "EF26",
    name: "Tratamento Acne ativa",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 365,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-292",
    externalCode: "EO1",
    name: "Tratamento Alopecia com Fototerapia (sessão)",
    categoryId: "cat-6",
    categoryName: "Outros",
    price: 250,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-293",
    externalCode: "EF36",
    name: "Tratamento Cicatriz de Acne",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 365,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-294",
    externalCode: "MP48",
    name: "Tratamento de Infecção",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 160,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-295",
    externalCode: "C58",
    name: "Tratamento Detox",
    categoryId: "cat-16",
    categoryName: "Tratamentos",
    price: 280,
    durationMinutes: 45,
    isActive: true,
  },
  {
    id: "srv-296",
    externalCode: "EC31",
    name: "Tratamento Estrias",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 116,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: "srv-297",
    externalCode: "PD002",
    name: "Tratamento para correção de unhas",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 100,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-298",
    externalCode: "EC47",
    name: "Ultrassom Corporal",
    categoryId: "cat-3",
    categoryName: "Corporal",
    price: 175,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-299",
    externalCode: "EF29",
    name: "Ultrassom Facial",
    categoryId: "cat-10",
    categoryName: "Facial",
    price: 110,
    durationMinutes: 25,
    isActive: true,
  },
  {
    id: "srv-300",
    externalCode: "MP50",
    name: "Unha em Gel",
    categoryId: "cat-7",
    categoryName: "Alongamento de Unhas",
    price: 90,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-301",
    externalCode: "MP51",
    name: "Unhas Inflamadas/Encravadas",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 130,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-302",
    externalCode: "MP53",
    name: "Verruga Plantar",
    categoryId: "cat-12",
    categoryName: "Podologia",
    price: 130,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "srv-303",
    externalCode: "DC50",
    name: "Virilha",
    categoryId: "cat-1",
    categoryName: "Com Ceras",
    price: 42,
    durationMinutes: 15,
    isActive: true,
  },
];

// Funções auxiliares
export function getServicesByCategory(categoryId: string): ServiceData[] {
  return importedServices.filter(
    (s) => s.categoryId === categoryId && s.isActive,
  );
}

export function searchServices(query: string): ServiceData[] {
  const q = query.toLowerCase();
  return importedServices.filter(
    (s) =>
      s.isActive &&
      (s.name.toLowerCase().includes(q) ||
        s.externalCode.toLowerCase().includes(q) ||
        s.categoryName.toLowerCase().includes(q)),
  );
}

export function getServiceById(id: string): ServiceData | undefined {
  return importedServices.find((s) => s.id === id);
}

export function getServiceByCode(code: string): ServiceData | undefined {
  return importedServices.find((s) => s.externalCode === code);
}
